package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("EFR12000Tap2Drive_EXT")
internal class EFR12000Tap2Drive_EXT {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
/*start00rule*/
    return messageContext.DestID == 15
/*end00rule*/
}

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*/
 
/*end00rule*/
  }
}
